### ISSUE TITLE
Locked Medicine effect persists between fights

### ISSUE THREAD

**Issue by KongMD-Steam** [Tempus/The-Disciple#1]
## Expected Behavior
The Locked Medicine replica effect, exhausting status cards as they are drawn, is only active when the replica is active.

## Actual Behavior
The locked medicine effect persists between battles and between entire games. It even persists after the replica has shattered. The effect does not persist between games if Slay the Spire is closed and re-opened. 

## Steps to Reproduce the Problem
* Start a new game
* Add Locked Medicine to your hand and play it
* End turn
* Kill your character with `kill self` command
* Start a new game from the main menu
* Add Dazed to your deck before entering combat with `deck add Dazed 6`
* Enter combat and draw a Dazed. Observe that the Locked Medicine effect is still active and exhausts them when drawn.

## Mods active
1) BaseMod 3.0.2
2) The Disciple 0.9.3

**Comment by Tempus** [comment]
Fixed in 0.9.4, thanks for the report Kong!
