### ISSUE TITLE
confusing or incorrect wording on chronometer and like effects

### ISSUE THREAD

**Issue by xcalibre0** [Tempus/The-Disciple#11]
Chronometer states that the cost reduction on the card is until it is "played".  If an effect other than retain, such as runic pyramid, holds a previously retained card then the cost of the card reverts back to normal; even though the card has not been played.  This is inconsistent with base cards that use the text "until played"

**Comment by Tempus** [comment]
Chronometer is expected behaviour, Runic Pyramid was not. It's now been changed to be congruent with expectations! Thanks for the report.
