### ISSUE TITLE
donu attacked me even though he was asleep

### ISSUE THREAD

**Issue by xcalibre0** [Tempus/The-Disciple#14]
1. played grave on a donu when donu had NO artifacts
2. donu showed the sleep intent
3. donu wacked me anyway

**Comment by xcalibre0** [comment]
lol 

I put donu to sleep when her intent was to buff, and she still hit me!

**Comment by Tempus** [comment]
Haha, that is hilarious. It looks like they are hardcoded to attack when their nextmove is set to 0. Fixed in upcoming 0.9.5, thanks for your diligence in reporting!
