### ISSUE TITLE
possibly unintended interation with draw down and oracle form

### ISSUE THREAD

**Issue by xcalibre0** [Tempus/The-Disciple#15]
I had one stack left of draw down

1. played oracle form
2. draw down debuff removed
3. oracle form effect set to 3 cards (makes sense)
4. all subsequent turns oracle stuck to 3 cards

Is it intended that the oracle buff returns to 4 after the draw down would have expired?

**Comment by Tempus** [comment]
This was unintended and is now fixed. Look forward to it in 0.9.5 and thanks!
