### ISSUE TITLE
oracle form and lightning replica strange interactions

### ISSUE THREAD

**Issue by xcalibre0** [Tempus/The-Disciple#16]
I sometimes get two cards at the beginning of my turn prior to oracle form selection.  The second card I get isnt necessarily a skill.

**Comment by xcalibre0** [comment]
if relevant my oracle buff is set to 3

**Comment by Tempus** [comment]
I believe this is fixed! I'm not entirely sure since I'm not sure what caused it, but I changed things and couldn't make it happen again. Look, uh... keep your eye on it next build?
