### ISSUE TITLE
Stunga On Awakened One

### ISSUE THREAD

**Issue by fkinghatesigningup** [Tempus/The-Disciple#26]
Some pretty interesting stuff happened when i killed first form of awakened one and then casted stunga.  Awakened one goes to next form without hp bar and when you echonomics stunga he only gets stunned for one turn.  Also was wondering if you know how to unlock a20 without climbing, would like to test the character on a20, thanks.

**Comment by Tempus** [comment]
Looking into it, you can open your Slay The Spire folder in steamapps, and in preferences will be "CHRONO_CLASS". Edit that in notepad, it has a field for Ascension_Level. Set to 20.

**Comment by fkinghatesigningup** [comment]
Thanks Tempus!

**Comment by Tempus** [comment]
Just a note, the current balance was set for A15, to be harder than vanilla characters. This was prior to A20 being released. I'm working on finalizing A20 balance now, which should overall increase the strength of the character a tad.

**Comment by Tempus** [comment]
Could not reproduce issue with Awakened one. Tried...

• Stunning him multiple times
• Stunning the Awakened one then killing first form while stunned
• Stunning him while he was transitioning
• Stunning him with Echo while transitioning
• Stunning him with and without echo after the transition

All the above worked as expected. Could you clarify?

**Comment by fkinghatesigningup** [comment]
i had the cultists alive, everything was stunlocked, i killed the awakened one's first form then stunga'd again

**Comment by Tempus** [comment]
Alright, this was finally found and fixed. Thanks for all the reports!
