### ISSUE TITLE
TimeEater Stun Lock

### ISSUE THREAD

**Issue by fkinghatesigningup** [Tempus/The-Disciple#27]
I had time-eater stun-locked with echonomics+, he was on 11 for his clock and i casted slime spray, it did cast twice and his clock was at 1 when my turn came around, not sure if intentional.  PS Sospirando+ may be broken I'm 2/8 on a20 tried to pull Sospirando off and got it 2/5.

**Comment by Tempus** [comment]
A Sospirando+ nerf is in the works, but it was hard to get enough evidence since few people seem to use the card. Thanks for supporting proof. 

As far as Echonomics+ goes, fixed and it is going into a hotfix shortly
