### ISSUE TITLE
Exploders Explode Through Stun

### ISSUE THREAD

**Issue by fkinghatesigningup** [Tempus/The-Disciple#32]
Had 1 Stun on Exploders on their exploding turn and it went through, ouch.  This doesn't seem intuitive.

**Comment by Tempus** [comment]
That's expected behaviour. Powers (such as the Cultist buff, Orb Walkers, Transient's countdown, Malleable, etc) continue to increment and function if the enemy is stunned or asleep. The exploders have a countdown power, so this falls under the same category.

**Comment by Tempus** [comment]
Closed due to lack of additional comments! Thanks for the report.
