### ISSUE TITLE
lots of crashes

### ISSUE THREAD

**Issue by xcalibre0** [Tempus/The-Disciple#35]
seems to be possibly related to interactions between echo forward and echonomics

**Comment by Tempus** [comment]
I have not been able to make any crashes occur after playing around with Echoward and Echonomics. Can you elaborate, share logs, or provide steps to reproduce? You can find old logs in your slay the spire folder.

**Comment by Tempus** [comment]
Echonomics is no longer the same card, so this issue is closed.
