### ISSUE TITLE
Hands Up debuff is lost if Recurrance is cast

### ISSUE THREAD

**Issue by SilentJ28** [Tempus/The-Disciple#39]
Cast Hands Up+ on an enemy. Cast Recurrance on the same enemy. The shackled debuff is gone and the enemy won't lose strength.

Cast Hands Up+ on an enemy. Cast Recurrance+ on the same enemy. The enemy actually gains 1 strength.

**Comment by Tempus** [comment]
Just fixed this yesterday actually! Thanks for the report, look forward to the fix in 0.9.7
