### ISSUE TITLE
Card conflicts with The Servant mod

### ISSUE THREAD

**Issue by SilentJ28** [Tempus/The-Disciple#40]
Fast Forward and Rewind have overlapping names that conflict with the cards from https://github.com/lionpkqq/StS-BlackRuseMod. I don't think I noticed an issue while playing the disciple, but while playing the Servant I was getting Disciple:Fast Forward and Rewind card test said it was providing -1 block instead of the normal positive amount

**Comment by Tempus** [comment]
No intention to fix this at this time, sorry.
