### ISSUE TITLE
Warpaint doesn't work with Ironclad

### ISSUE THREAD

**Issue by SilentJ28** [Tempus/The-Disciple#41]
I have the warpaint+ card on ironclad. On cast it upgrades all skills in hand, but the passive effect doesn't trigger on any future turns. So no more skill upgrades on following turns.

I assume the same would be the case for any other replicas as there is probably an extra handler for them on the disciple

**Comment by Tempus** [comment]
Just for whetstone+ thankfully! Fixed in 0.9.8 and thanks for the report!
