### ISSUE TITLE
[x-Replay the Spire] Curse of Delerium was able to give character confusion, despite Chronometer relic

### ISSUE THREAD

**Issue by silasary** [Tempus/The-Disciple#5]
When playing with the [Replay the Spire](https://github.com/AstroPenguin642/Replay-the-Spire) mod enabled, one of its curses, [Delerium](https://github.com/AstroPenguin642/Replay-the-Spire/blob/master/src/main/java/com/megacrit/cardcrawl/cards/curses/Delirium.java), was able to give my character Confusion, despite having the Chronometer relic at the time.

I'm not sure if this is something to fix on your end or their end, so I'll also open an issue there.

**Comment by Tempus** [comment]
I've improved confusion prevention, it will take effect in 0.9.4! Thanks a lot and look forward to it.
