### ISSUE TITLE
Putting lagavulin to sleep

### ISSUE THREAD

**Issue by Thunderbolt33** [Tempus/The-Disciple#52]
I put lagavulin to sleep with Grave on the first turn he intended to attack, and went to retain a card, but when the retain screen came up, the Sleep wore off and he attacked me.

**Comment by Tempus** [comment]
Did you perchance have a relic such as Mercury Hourglass, Mercury?, or Letter Opener, or a replica like  Locked Mercury?

**Comment by Thunderbolt33** [comment]
I believe what happened is I probably played a strike afterwards and forgot about it, because putting him to sleep later didn't have the same effect. my bad

**Comment by Tempus** [comment]
No worries, I often forget about damage and wake people up by accident, haha
