### ISSUE TITLE
Conflict with MadScienceMod

### ISSUE THREAD

**Issue by twanvl** [Tempus/The-Disciple#6]
I noticed that the disciple uses the color BRONZE for its cards, but so the the Mad Scientist. So the card and relic pools get mixed together if both mods are installed.

**Comment by Tempus** [comment]
This will be fixed shortly, as basemod is now forcing compendium tabs to be named after the character anyway and not drawn directly from the enum name.

**Comment by Tempus** [comment]
This is finally resolved and will be implemented in 0.9.8.
