### ISSUE TITLE
Unique ID for cards

### ISSUE THREAD

**Issue by rainfoxest** [Tempus/The-Disciple#61]
It is a good practice to have its unique ID for most of the things, including cards.
If any mods show the same ID with your mod, their loc will be conflict and get overwrited.

e.g.
The card "Fast Forward" have the ID "FastForward", and so is the mod [BlackRuseMod](https://github.com/lionpkqq/StS-BlackRuseMod), so your mod and his mod have a conflict, and this card string get mess up.

In some mods (like [Slimebound](https://github.com/mikemayhemdev/SlimeboundMod)), they name the ID like "Slimebound:LevelUp" for the card "Level Up".

**Comment by Tempus** [comment]
This mod predates that convention by a few months, as does Servant. Changing the IDs would mess up my metrics, so I don't have any intention to change them in the short term. That specific conflict is fixed in the next version. Thanks for the report.
